config/routes.rb
Rails.application.routes.draw do
  root 'slides#index'

  resources :slides
  get '/admin' => 'slides#admin'
  post 'slides/publish' => 'slides#publish'
  post 'slides/unpublish' => 'slides#unpublish'


end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/slide.rb
class Slide < ApplicationRecord
  include AASM

  mount_uploader :client_logo, LogoUploader
  mount_uploader :image, ImageUploader

  validates :client_name, :client_logo, :project_title, :description, :image, presence: true
  validates :description, length: {maximum: 1000}

  aasm do
    state :draft, initial: true
    state :online

    event :go_online do
      transitions from: :draft, to: :online
    end

    event :go_offline do
      transitions from: :online, to: :draft
    end

  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/slides_controller.rb
class SlidesController < ApplicationController
  before_action :find_slide, except: [:index, :new, :create, :admin]
  http_basic_authenticate_with name: ENV['ADMIN_NAME'], password: ENV['ADMIN_PASSWORD'], except: :index

  def index
    @slides = Slide.online.sort
  end

  def new
    @slide = Slide.new
  end

  def create
    @slide = Slide.new(slide_params)

    if @slide.save
      flash[:notice] = "Le Slide #{@slide.id} a bien été créé"
      redirect_to admin_path
    else
      render 'new'
    end
  end

  def edit
  end

  def update
    if @slide.update(slide_params)
      flash[:notice] = "Le Slide #{@slide.id} a bien été mis à jour"
      redirect_to admin_path
    else
      render 'edit'
    end
  end

  def destroy
    @slide.destroy
    flash[:notice] = "Le Slide #{@slide.id} a bien été supprimé"
    redirect_to admin_path
  end

  def admin
    @slides = Slide.all.sort
  end

  def publish
    @slide = Slide.find(params[:id])

    @slide.go_online!
    flash[:notice] = "Le Slide #{@slide.id} est maintenant publié"
    redirect_to admin_path
  end

  def unpublish
    @slide = Slide.find(params[:id])

    @slide.go_offline!
    flash[:notice] = "Le Slide #{@slide.id} est maintenant offline"
    redirect_to admin_path
  end

  private

  def slide_params
    params.require(:slide).permit(:client_name, :client_logo, :project_title, :description, :image)
  end

  def find_slide
    @slide = Slide.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/slides_helper.rb
module SlidesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Sliders</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
  </head>

  <body class="<%= controller.controller_name %> <%= controller.action_name %>">
    <div class="alert-success text-center"><strong><%= notice %><%= alert %></strong></div>

    <div class="container">
      <%= yield %>
    </div>
  </body>
</html>

app/views/slides/_form.html.erb
<script src="//cdn.tinymce.com/4/tinymce.min.js"></script>
<script>tinymce.init({ selector:'textarea' });</script>

<div class="container">
  <%= simple_form_for @slide do |f| %>
    <%= f.input :client_name %>
    <%= f.input :client_logo %>
    <%= f.input :project_title %>
    <%= f.input :description, input_html: {class:"tinymce", rows: 4, cols: 120} %>
    <%= f.input :image %>
    <%= f.button :submit %>
  <% end %>
</div>

app/views/slides/_slide_card.html.erb
<% @slides.each do |s| %>
  <div>
    <div class="col-xs-12 col-md-5">
      <div class="col-xs-8">
        <%= s.id %> <%= s.client_name %>
      </div>
      <div class="col-xs-4">
        <%= image_tag (s.client_logo) %>
      </div>
      <h2 class="margin_top_60"> <%= s.project_title %></h2>

      <article ><%= s.description.html_safe %></article>
    </div>

    <div class="col-xs-12 col-md-7 margin_top_30">
      <%= image_tag s.image, class:'img-responsive center-block' %>
    </div>
  </div>
<% end %>

app/views/slides/admin.html.erb
<h1 class="text-center">Back Office</h1>

<%= link_to 'Créer un nouveau Slide', new_slide_path, class:'btn btn-default' %>

<h3>Liste</h3>

<% if Slide.exists? %>
  <% @slides.each do |s| %>
  <div class= "col-xs-6 col-md-3" >

    <p>Id : <strong><%= s.id %></strong> </p>
    <p>Client Name : <strong> <%= s.client_name %> </strong> </p>
    <p>Logo : <%= image_tag s.client_logo, class:'logo' %></p>

    <%= link_to 'Editer', edit_slide_path(s.id) %>
    <%= link_to 'Supprimer', slide_path(s), method: :delete, data: { confirm: "Confirmez vous la suppresion de ce slide ?"} %><br>
    <%= link_to 'Preview', slide_path(s.id) %>
    <% if s.draft? %>
      <%= button_to "Mettre en ligne", {:controller => :slides, :action => 'publish', :id => s.id }, :method => :post %>
    <% else %>
      <%= button_to "Mettre Offline", {:controller => :slides, :action => 'unpublish', :id => s.id }, :method => :post %>
    <% end %>

  </div>
  <% end %>
<% end %>

app/views/slides/edit.html.erb
<h1>Modifier Slide N°<%= @slide.id %></h1>

<%= render 'form' %>

app/views/slides/index.html.erb
<div class="owl-carousel margin_top_60">
  <%= render 'slide_card' %>
</div>

<%= javascript_include_tag 'home_slide.js' %>

app/views/slides/new.html.erb
<h1>Créer un nouveau Slide</h1>

<%= render 'form' %>

app/views/slides/show.html.erb
<div class="margin_top_60">
  <div class="col-xs-12 col-md-5">
    <div class="col-xs-8">
      <%= @slide.id %> <%= @slide.client_name %>
    </div>
    <div class="col-xs-4">
      <%= image_tag (@slide.client_logo) %>
    </div>

    <h2 class="margin_top_60"> <%= @slide.project_title %></h2>
    <article><%= @slide.description.html_safe %></article>
  </div>

  <div class="col-xs-12 col-md-7 margin_top_30">
    <%= image_tag @slide.image, class:'img-responsive center-block' %>
  </div>
</div>

<div class="text-center col-xs-12 margin_top_60">
  <%= link_to 'Retour', admin_path, class:"btn btn-default" %>
</div>